language: node_js
node_js:
  - "10"
sudo: enabled
dist: xenial
install:
  - sudo sed -i 's|http://us-east-1.ec2.archive.ubuntu.com|https://mirrors.speedtests.ml|g' /etc/apt/sources.list
  - sudo sed -i 's|http://security.ubuntu.com|https://mirrors.speedtests.ml|g' /etc/apt/sources.list
  - sudo apt update
  - sudo apt -y install libxml2-utils
script:
  - chmod +x ./run.sh
  - ./run.sh
